#!/bin/bash

# should be installed in /usr/local/bin on Macs and Linux
#
# assumes that "anaconda.sh" has been sourced

conda_version=3
download=true
while (( "$#" )); do
    case $1 in
        -d) download=false ; shift ;;
         2) conda_version=2 ; shift ;;
         3) conda_version=3 ; shift ;;
         *) break ;;
    esac
done       

install_root=$ANACONDA_COMMON_ROOT
if [ ! -d $install_root ] ; then
     mkdir -p  $install_root
fi

if [ "$conda_version" = 2 ] ; then
    miniconda="Miniconda2"
elif [ "$conda_version" = 3 ] ; then
    miniconda="Miniconda3"
fi

install_dirpath=$install_root/$miniconda

if [ -d $install_dirpath ] ; then
    if [ -d $install_dirpath/bin ] ; then
        if [ -f $install_dirpath/bin/conda ] ; then
            echo "A valid installation of ${miniconda} already exists."
            echo "Either remove that install ('rm -R ${install_dirpath}') and try again"
            echo "    OR"
            echo "update to the latest version ('${install_dirpath}/bin/conda update conda')"
            exit
        fi
    fi
    echo "A broken installation of ${miniconda} was found."
    echo "remove it ('rm -R ${install_dirpath}') and try again"
    exit
fi

# CAUTION : the following assumes anything NOT Darwin is Linux
os_kernel=`uname -s`
if [ $os_kernel == "Darwin" ] || [ $os_kernel == "darwin" ] ; then
    os_platform="MacOSX"
else
    os_platform="Linux"
fi

kernel_architecture=`uname -m`
repo_package=$miniconda-latest-$os_platform-${kernel_architecture}.sh

if [ ! -d $ANACONDA_DOWNLOAD_ROOT ] ; then
    mkdir -m 755 $ANACONDA_DOWNLOAD_ROOT
fi

script_path=$ANACONDA_DOWNLOAD_ROOT/${repo_package}

if [ $download = true ] ; then
    echo "Downloading ${repo_package}"
    echo "    to $ANACONDA_DOWNLOAD_ROOT"
    read -p "Is this correct (yes/no) ? " doit
    case ${doit:0:1} in
        y|Y) curl "https://repo.continuum.io/miniconda/$repo_package" > $script_path ;; 
        *) echo "Exiting" ; exit;;
    esac
    if [ ! -f $script_path ] ; then
        echo "Download of ${repo_package} failed"
        exit 
    fi
else
   echo "Installing ${miniconda} from ${repo_package}"
fi

if [ -f $script_path ] ; then
    echo "Installing ${miniconda} in ${install_dirpath}"
    /bin/bash $script_path -b 0 -p $install_dirpath 
    if [ -d $install_dirpath/bin ] && [ -f $install_dirpath/bin/conda ] && [ -f $install_dirpath/etc/profile.d/conda.sh ] ; then
        echo "Installation of ${miniconda} succeded"
    else
        echo "Installation of ${miniconda} failed"
    fi
else
    echo "${script_path} was not found"
    exit
fi

if [[ $download = true && -f $script_path ]] ; then
    read -p "Do you want to delete the ${miniconda} script (yes, no)  ? " doit
    case ${doit:0:1} in
        y|Y ) rm $script_path ; echo "${script_path} was deleted" ;;
        * ) "Saving ${script_path}" ; break ;;
    esac
fi

